apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: ansible-builder-example
spec:
  source:
    url: https://github.com/dbarreda/ansible-builder-shipwright
    contextDir: example-builder
    revision: main
  output:
    image: image-registry.openshift-image-registry.svc:5000/ansible-builder-shipwright/ansible-builder-shipwright-example-ee:latest
    pushSecret: pushsecret
  strategy:
    name: ansible-builder
    kind: ClusterBuildStrategy
